# Generated by Django 4.2.3 on 2023-07-19 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="wiriter",
            new_name="writer",
        ),
    ]
