# Generated by Django 4.2.3 on 2023-07-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_rename_wiriter_comment_writer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("bno", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=250)),
                ("author", models.CharField(max_length=500)),
                ("price", models.IntegerField(default=0)),
                ("point", models.FloatField(default=0.0)),
            ],
        ),
    ]
